### ISSUE TITLE
CMake build fails with `Use full profile as baremetal profile is not supported for this Mbed target`

### ISSUE THREAD

**Issue by Patater** [ARMmbed/mbed-os-example-blinky-baremetal#55] opened 2021-04-08 13:01 UTC
### Description of defect

```
#### STDERR ####

#### End of STDOUT/STDERR ####

[EXAMPLES]> WARNING  Test for mbed-os-example-blinky will not be generated.
[EXAMPLES]> INFO     In folder 'mbed-os-example-blinky-baremetal'
[EXAMPLES]> INFO     Compiling mbed-os-example-blinky-baremetal ARCH_PRO GCC_ARM
[EXAMPLES]> INFO     Executing command 'mbed-tools compile -t GCC_ARM -m ARCH_PRO -c'...

#### STDOUT ####
Configuring project and generating build system...
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/local/gcc-arm-none-eabi-9-2019-q4-major/bin/arm-none-eabi-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/gcc-arm-none-eabi-9-2019-q4-major/bin/arm-none-eabi-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/gcc-arm-none-eabi-9-2019-q4-major/bin/arm-none-eabi-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /usr/bin/python3.7 (found version "3.7.4") found components: Interpreter 
-- Checking for Python package prettytable -- found
-- Checking for Python package future -- found
-- Checking for Python package jinja2 -- found
-- Checking for Python package intelhex -- found
-- Configuring incomplete, errors occurred!
See also "/builds/workspace/mbed-os-ci_cmake-example-GCC_ARM-dev@5/examples/mbed-os-example-blinky-baremetal/cmake_build/ARCH_PRO/develop/GCC_ARM/CMakeFiles/CMakeOutput.log".
See also "/builds/workspace/mbed-os-ci_cmake-example-GCC_ARM-dev@5/examples/mbed-os-example-blinky-baremetal/cmake_build/ARCH_PRO/develop/GCC_ARM/CMakeFiles/CMakeError.log".

#### STDERR ####
CMake Error at mbed-os/CMakeLists.txt:233 (message):
  Use full profile as baremetal profile is not supported for this Mbed target
Call Stack (most recent call first):
  mbed-os/CMakeLists.txt:250 (mbed_validate_application_profile)
  CMakeLists.txt:30 (mbed_set_post_build)


ERROR: CMake invocation failed!
```

#### Target(s) affected by this defect ?
ARCH_PRO
LPC1768

#### Toolchain(s) (name and version) displaying this defect ?
GCC_ARM

#### What version of Mbed-os are you using (tag or sha) ?

9bbc8c914c7e 

#### What version(s) of tools are you using. List all that apply (E.g. mbed-cli)
Mbed CLI 2

#### How is this defect reproduced ?
`mbed-tools compile -t GCC_ARM -m ARCH_PRO -c`

**Comment by ciarmcom** [comment] 2021-04-08 13:42
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-3790*

**Comment by LDong-Arm** [comment] 2021-04-08 16:16
The issue is missing declarations of bare-metal support in Mbed OS `targets.json`. Mbed CLI 1 doesn't enforce profile check whereas Mbed CLI 2 does, which is an improvement.

It's fixed by https://github.com/ARMmbed/mbed-os/pull/14359 after review comments are addressed.

**Closed as completed** 2021-04-13 08:58 UTC
Labels: type: bug, Jira status: DONE
